# Generated by Django 4.2.4 on 2023-12-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_basemax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
